package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/misc-lab/ldap-admin-tool/internal/config"
	ldapclient "github.com/misc-lab/ldap-admin-tool/internal/ldap"
	"github.com/misc-lab/ldap-admin-tool/internal/password"
)

var modifyUID string

var modifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Modify an LDAP user account",
	Long:  "Modify user password, email, and group memberships.",
}

var modifyPasswordCmd = &cobra.Command{
	Use:   "password [password]",
	Short: "Change a user's password",
	Long:  "Change a user's password. If no password is provided, a new one will be auto-generated.",
	Args:  cobra.MaximumNArgs(1),
	Example: `  ldap-admin-tool user modify password --uid ftotti "NewP@ss1!"
  ldap-admin-tool user modify password --uid ftotti  # auto-generates`,
	RunE: runModifyPassword,
}

var modifyEmailCmd = &cobra.Command{
	Use:   "email <email>",
	Short: "Change a user's email",
	Args:  cobra.ExactArgs(1),
	Example: `  ldap-admin-tool user modify email --uid ftotti new@misc-lab.org`,
	RunE: runModifyEmail,
}

var modifyAddGroupCmd = &cobra.Command{
	Use:   "add-group <group> [group ...]",
	Short: "Add a user to one or more groups",
	Args:  cobra.MinimumNArgs(1),
	Example: `  ldap-admin-tool user modify add-group --uid ftotti printing-b
  ldap-admin-tool user modify add-group --uid ftotti printing-b admins-cups`,
	RunE: runModifyAddGroup,
}

var modifyRemoveGroupCmd = &cobra.Command{
	Use:   "remove-group <group> [group ...]",
	Short: "Remove a user from one or more groups",
	Args:  cobra.MinimumNArgs(1),
	Example: `  ldap-admin-tool user modify remove-group --uid ftotti printing-a
  ldap-admin-tool user modify remove-group --uid ftotti printing-a printing-b`,
	RunE: runModifyRemoveGroup,
}

func init() {
	modifyCmd.PersistentFlags().StringVar(&modifyUID, "uid", "", "Username / uid (required)")
	modifyCmd.MarkPersistentFlagRequired("uid")

	modifyCmd.AddCommand(modifyPasswordCmd)
	modifyCmd.AddCommand(modifyEmailCmd)
	modifyCmd.AddCommand(modifyAddGroupCmd)
	modifyCmd.AddCommand(modifyRemoveGroupCmd)
}

func runModifyPassword(cmd *cobra.Command, args []string) error {
	return withLDAPClient(func(cfg *config.Config, client *ldapclient.Client) error {
		userPass := ""
		autoGenerated := len(args) == 0
		if autoGenerated {
			var err error
			userPass, err = password.Generate(12)
			if err != nil {
				return fmt.Errorf("failed to generate password: %w", err)
			}
		} else {
			userPass = args[0]
		}

		if err := client.ChangePassword(modifyUID, userPass); err != nil {
			return err
		}

		rows := []string{
			"Username", modifyUID,
			"Password", userPass,
		}
		if autoGenerated {
			rows = append(rows, "Note", "auto-generated — communicate securely to user")
		}
		printBanner("Password changed successfully!", rows...)

		return nil
	})
}

func runModifyEmail(cmd *cobra.Command, args []string) error {
	return withLDAPClient(func(cfg *config.Config, client *ldapclient.Client) error {
		newEmail := args[0]

		if err := client.ChangeEmail(modifyUID, newEmail); err != nil {
			return err
		}

		printBanner("Email changed successfully!",
			"Username", modifyUID,
			"Email", newEmail)

		return nil
	})
}

func runModifyAddGroup(cmd *cobra.Command, args []string) error {
	return withLDAPClient(func(cfg *config.Config, client *ldapclient.Client) error {
		printProgress("Adding user to groups...")

		for _, group := range args {
			if err := client.AddToGroup(modifyUID, group); err != nil {
				fmt.Printf("  [!] %v\n", err)
			} else {
				fmt.Printf("  [+] Added to group '%s'\n", group)
			}
		}

		printDone()

		return nil
	})
}

func runModifyRemoveGroup(cmd *cobra.Command, args []string) error {
	return withLDAPClient(func(cfg *config.Config, client *ldapclient.Client) error {
		printProgress("Removing user from groups...")

		for _, group := range args {
			if err := client.RemoveFromGroup(modifyUID, group); err != nil {
				fmt.Printf("  [!] %v\n", err)
			} else {
				fmt.Printf("  [-] Removed from group '%s'\n", group)
			}
		}

		printDone()

		return nil
	})
}
